<?php
$_product = $block->getProduct();
if ( !empty(trim($_product->getData('tag'))) ):
    $tags = explode(',', $_product->getData('tag'));
?>
<div class="product-tags">
    <?php foreach ($tags as $tag): ?>
    <span><?= $tag?></span>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $('.product-tags').insertBefore('.product-info-price');
    });
</script>
<?php endif;?>