<?php
/**
 * Copyright © Ulmod. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php if ($comment = $block->getOrderComment()): ?>
    <section class="admin__page-section um-ordercomment">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Order Comment')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <?= nl2br($block->escapeHtml($comment)) ?>
        </div>
    </section>
<?php endif; ?>
