<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magento\OfflinePayments\Block\Info\Purchaseorder
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <strong><?= $block->escapeHtml(__('I need a \'PayPal Request For Money\'')) ?></strong>
        <span class="number"><?= $block->escapeHtml($block->getInfo()->getPoNumber()) ?></span>
    </dd>
</dl>