<div class="block">
    <div class="block-title"><strong>Unsere Standorte</strong></div>
    <div class="row">
        <div class="col-lg-4">
            <div class="block">
                <div class="block-content">
                    <h3>City 1</h3>
                    <div class="shop-address">
                        <strong>The Zentrale</strong>
                        <p>Address 1</p>
                        <p>Address 2</p>
                    </div>
                    <div class="shop-contact">
                        <p>Tel.: 5555 - 555 555</p>
                        <p><a href="mailto:mail@mail.de">mail@mail.de</a></p>
                    </div>
                    <div class="open-hours">
                        <p>Öffnungszeiten:</p>
                        <p>Mo-Fr 10:00 bis 17:00 Uhr</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="block">
                <div class="block-content">
                    <h3>City 2</h3>
                    <div class="shop-address">
                        <strong>The Zentrale</strong>
                        <p>Address 1</p>
                        <p>Address 2</p>
                    </div>
                    <div class="shop-contact">
                        <p>Tel.: 5555 - 555 555</p>
                        <p><a href="mailto:mail@mail.de">mail@mail.de</a></p>
                    </div>
                    <div class="open-hours">
                        <p>Öffnungszeiten:</p>
                        <p>Mo-Fr 10:00 bis 17:00 Uhr</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="block">
                <div class="block-content">
                    <h3>City 3</h3>
                    <div class="shop-address">
                        <strong>The Zentrale</strong>
                        <p>Address 1</p>
                        <p>Address 2</p>
                    </div>
                    <div class="shop-contact">
                        <p>Tel.: 5555 - 555 555</p>
                        <p><a href="mailto:mail@mail.de">mail@mail.de</a></p>
                    </div>
                    <div class="open-hours">
                        <p>Öffnungszeiten:</p>
                        <p>Mo-Fr 10:00 bis 17:00 Uhr</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>