<div class="product-side-info">
    <img class="info-logo" src="{{media url=&quot;logo/logo_freeshipping.jpg&quot;}}" alt="" />
    <ul class="info-items">
        <li>
            <i class="png-icon-visa"></i>
            <span>Accept Payments online</span>
        </li>
        <li>
            <i class="png-icon-money"></i>
            <span>Money back guarantee</span>
        </li>
        <li>
            <i class="png-icon-calculator"></i>
            <span>Calculate shipping cost</span>
        </li>
        <li>
            <i class="png-icon-check"></i>
            <span>Ships items quickly</span>
        </li>
        <li>
            <i class="png-icon-delivery"></i>
            <span>Same-day delivery</span>
        </li>
    </ul>
    <div class="manufacter-info">
        <span class="store-logo"><i class="png-icon-store"></i></span>
        <div class="store-info">
            <span class="meta-title">Manufactured By</span>
            <span class="store-name">Footwear Store</span>
            <span class="score">0 / 5</span>
        </div>
        <a class="store-link" href="#">Contact Us</a>
    </div>
</div>
