<div class="custom-block" style="padding-bottom: 10px;">
    <div class="custom-block-title">Zahlungsmöglichkeiten</div>
    <div class="custom-block-payment-logos">
        <img src="{{media url="wysiwyg/gastro/paypal.png"}}"/>
        <img src="{{media url="wysiwyg/gastro/vorkasse.png"}}"/>
        <img src="{{media url="wysiwyg/gastro/mastercard.png"}}"/>
        <img src="{{media url="wysiwyg/gastro/visa-alternate.png"}}"/>
        <img src="{{media url="wysiwyg/gastro/klarna-ratenkauf-alt.png"}}"/>
    </div>
</div>
<div class="custom-block">
    <div class="custom-block-title">Kundenservice</div>
    <div>
        <p>Fragen zum Produkt? Wir sind von Mo bis Fr 10:00 bis 17:00 Uhr telefonisch erreichbar</p>
        <strong>03 53 3 - 163 110</strong>
    </div>
</div>
<img src="{{media url="wysiwyg/gastro/product-side-banner.jpg"}}"/>
