<div style="background-color:#f4f4f4;">
    <div class="container">
        <div class="homepage-bar" style="margin:0;">
            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <i class="png-icon-homebar1"></i>
                    <div class="text-area">
                        <h3>FREE SHIPPING & RETURN</h3>
                        <p>Free shipping on all orders over $99.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <i class="png-icon-homebar2"></i>
                    <div class="text-area">
                        <h3>MONEY BACK GUARANTEE</h3>
                        <p>100% money back guarantee.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <i class="png-icon-homebar3"></i>
                    <div class="text-area">
                        <h3>ONLINE SUPPORT 24/7</h3>
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>