<div class="block">
    <div class="block-title"><strong>Kundenservice</strong></div>
    <div class="block-content">
        <ul class="links">
            <li><i class="porto-icon-angle-right"></i><a href="#">Zahlungsarten</a></li>
            <li><i class="porto-icon-angle-right"></i><a href="#">Versandarten</a></li>
            <li></li>
            <li><i class="porto-icon-angle-right"></i><a href="#">Kontakt</a></li>
            <li><i class="porto-icon-angle-right"></i><a href="#">Impressum</a></li>
            <li><i class="porto-icon-angle-right"></i><a href="#">AGB</a></li>
        </ul>
    </div>
</div>