<div class="home-top-container">
	<div class="home-category">
		<div class="home-side-menu">
			{{block class="Smartwave\Megamenu\Block\Topmenu" name="sw.sidenav" template="Smartwave_Megamenu::sidemenu.phtml" ttl="3600"}}
		</div>
	</div>
	<div class="home-banner-main">
		<div id="banner-slider-demo-9" class="owl-carousel owl-banner-carousel owl-bottom-narrow" style="margin-bottom:20px;">
			<div class="item" style="background:url({{media url="wysiwyg/gastro/homepage/shutterstock_1306579120.jpg"}}) center center no-repeat;background-size:cover;border-radius:2px;">
				<div style="position:relative">
					<img src="{{media url="wysiwyg/gastro/homepage/02.png"}}" alt="" />
					<div class="content content-slide-1" style="top:9%;left:5%;">
						<span style="font-weight: 300">UNSERE</span>
						<h2>EDELSTAHLMÖBEL</h2>
					</div>
				</div>
			</div>
			<div class="item" style="background:url({{media url="wysiwyg/gastro/homepage/shutterstock_1306579120.jpg"}}) center center no-repeat;background-size:cover;border-radius:2px;">
				<div style="position:relative">
					<img src="{{media url="wysiwyg/gastro/homepage/02.png"}}" alt="" />
					<div class="content content-slide-2" style="position:absolute;z-index:1;top:23%;left:8%;text-align:left;">
						<span style="font-size:18px;">OVER <b style="font-size:26px;font-family:'Oswald';">200+</b></span>
						<h2>GREAT DEALS</h2>
						<p style="font-size:14px;font-weight:300;">While they last!</p>
						<a href="{{config path="web/unsecure/base_url"}}electronics.html" class="btn btn-default" style="background-color:#010204;color:#fff;font-family:'Oswald';font-size:14px;letter-spacing:0.025em;font-weight:400;">shop now</a>
					</div>
				</div>
			</div>
			<div class="item" style="background:url({{media url="wysiwyg/gastro/homepage/shutterstock_1306579120.jpg"}}) center center no-repeat;background-size:cover;border-radius:2px;">
				<div style="position:relative">
					<img src="{{media url="wysiwyg/gastro/homepage/02.png"}}" alt="" />
					<div class="content content-slide-3" style="position:absolute;z-index:1;top:23%;left:8%;text-align:left;">
						<span style="font-size:18px;">up to <b style="font-size:26px;font-family:'Oswald';">40%</b> off</span>
						<h2>NEW ARRIVALS</h2>
						<p style="font-size:14px;font-weight:300;">Starting at $9</p>
						<a href="{{config path="web/unsecure/base_url"}}motors.html" class="btn btn-default" style="background-color:#010204;color:#fff;font-family:'Oswald';font-size:14px;letter-spacing:0.025em;font-weight:400;">shop now</a>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			require([
				'jquery',
				'owl.carousel/owl.carousel.min'
			], function ($) {
				$("#banner-slider-demo-9").owlCarousel({
					items: 1,
					autoplay: true,
					autoplayTimeout: 5000,
					autoplayHoverPause: true,
					dots: false,
					nav: false,
					navRewind: true,
					animateIn: 'fadeIn',
					animateOut: 'fadeOut',
					loop: true
				});
			});
		</script>
	</div>
    <div class="home-banner-right">
        <div id="ads-slider-demo-9" class="owl-carousel">
            <div class="item">
                <img src="{{media url="wysiwyg/gastro/homepage/shutterstock_1071810413.jpg"}}" alt="" style="display:inline-block;"/>
                <div class="content ads-slide-1" style="bottom:6%;left:7%;">
                    <span style="font-weight: 300">DEINE</span>
                    <h2>KOCHTECHNIK</h2>
                </div>
            </div>
            <div class="item">
                <img src="{{media url="wysiwyg/gastro/homepage/shutterstock_1071810413.jpg"}}" alt="" style="display:inline-block;" />
                <div class="content ads-slide-2" style="bottom:6%;left:7%;">
                    <span style="font-weight: 300">DEINE</span>
                    <h2>KOCHTECHNIK</h2>
                </div>
            </div>
            <div class="item">
                <img src="{{media url="wysiwyg/gastro/homepage/shutterstock_1071810413.jpg"}}" alt="" style="display:inline-block;" />
                <div class="content ads-slide-3" style="bottom:6%;left:7%;">
                    <span style="font-weight: 300">DEINE</span>
                    <h2>KOCHTECHNIK</h2>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            require([
                'jquery',
                'owl.carousel/owl.carousel.min'
            ], function ($) {
                $("#ads-slider-demo-9").owlCarousel({
                    items: 1,
                    autoplay: true,
                    autoplayTimeout: 5000,
                    autoplayHoverPause: true,
                    dots: false,
                    nav: false,
                    navRewind: true,
                    animateIn: 'fadeIn',
                    animateOut: 'fadeOut',
                    loop: true
                });
            });
        </script>
    </div>
</div>
<div class="latest-products-wrapper" style="background-color:#fff; margin-top:13px;">
    <h2 class="filterproduct-title"><span class="content"><strong>Gebrauchtgeräte</strong></span></h2>
    <div id="latest_products" class="owl-top-narrow">
        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_product" category_id="4" product_count="12" column_count="6" aspect_ratio="0" image_width="250" image_height="250" product_type="9" template="owl_list.phtml"}}
    </div>
    <script type="text/javascript">
        require([
            'jquery',
            'owl.carousel/owl.carousel.min'
        ], function ($) {
            $("#latest_products .owl-carousel").owlCarousel({
                autoplay: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                loop: true,
                navRewind: true,
                margin: 0,
                nav: false,
                navText: ["<em class='porto-icon-left-open-huge'></em>","<em class='porto-icon-right-open-huge'></em>"],
                dots: false,
                responsive: {
                    0: {
                        items:2
                    },
                    768: {
                        items:3
                    },
                    992: {
                        items:4
                    },
                    1200: {
                        items:6
                    }
                }
            });
        });
    </script>
</div>
<div class="recent-posts">
    <div id="latest_news" class="row">
        <div class="col-md-6 col-lg-3">
            <div class="post-image">
                <img src="{{media url="wysiwyg/gastro/homepage/blog_thumb1.jpg"}}" alt="">
                <div class="postTitle">
                    <span>PROFESSIONELLE</span>
                    <strong>GROßKÜCHENPLANUNG</strong>
                </div>
            </div>
            <div class="post-content">
                <div class="postContent"><p>Planen Sie von Beginn an Ihr Projekt mit asGastro und profitieren Sie von unserer langjährigen Erfahrung.</p></div>
                <a class="read-more" href="#"><i class="porto-icon-right-open"></i></a>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="post-image">
                <img src="{{media url="wysiwyg/gastro/homepage/blog_thumb2.jpg"}}" alt="">
                <div class="postTitle">
                    <span>LEASING</span>
                    <strong>FÜR GROßGERÄTE</strong>
                </div>
            </div>
            <div class="post-content">
                <div class="postContent"><p>Mit unseren flexiblen Leasingangeboten bestimmen Sie die Laufzeit und die Höhe Rate einfach selber.</p></div>
                <a class="read-more" href="#"><i class="porto-icon-right-open"></i></a>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="post-image">
                <img src="{{media url="wysiwyg/gastro/homepage/blog_thumb3.jpg"}}" alt="">
                <div class="postTitle">
                    <span>VERMIETUNG</span>
                    <strong>FÜR FILMPRODUKTIONEN</strong>
                </div>
            </div>
            <div class="post-content">
                <div class="postContent"><p>Für Filmproduktionen und Großevents vermieten wir von der Gabel bis zur kompletten Küche alles was Sie brauchen.</p></div>
                <a class="read-more" href="#"><i class="porto-icon-right-open"></i></a>
            </div>
        </div>
        <div class="col-md-6 col-lg-3">
            <div class="post-image">
                <img src="{{media url="wysiwyg/gastro/homepage/blog_thumb4.jpg"}}" alt="">
                <div class="postTitle">
                    <span>EDELSTAHLMÖBEL</span>
                    <strong>EIGENE FERTIGUNG</strong>
                </div>
            </div>
            <div class="post-content">
                <div class="postContent"><p>Edelstahlmöbel nach Maß und „Made in Germany“. Gehen Sie keine Kompromisse bei der Qualität ein.</p></div>
                <a class="read-more" href="#"><i class="porto-icon-right-open"></i></a>
            </div>
        </div>
    </div>
</div>
<div class="featured-products-wrapper">
    <h2 class="filterproduct-title"><span class="content"><strong>spezialgeräte</strong></span></h2>
    <div id="featured_products" class="owl-top-narrow">
        {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="12" column_count="6" aspect_ratio="1" image_width="200" product_type="9" template="owl_list.phtml"}}
    </div>
    <script type="text/javascript">
        require([
            'jquery',
            'owl.carousel/owl.carousel.min'
        ], function ($) {
            $("#featured_products .owl-carousel").owlCarousel({
                autoplay: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                loop: true,
                navRewind: true,
                margin: 0,
                nav: false,
                navText: ["<em class='porto-icon-left-open-huge'></em>","<em class='porto-icon-right-open-huge'></em>"],
                dots: false,
                responsive: {
                    0: {
                        items:2
                    },
                    768: {
                        items:3
                    },
                    992: {
                        items:4
                    },
                    1200: {
                        items:6
                    }
                }
            });
        });
    </script>
</div>

<div class="container" style="padding-top: 32px;padding-bottom: 32px;">
    <div class="brands-slider-section">
        <div id="brands-slider" class="brands-slider" style="text-align: center;">
            <div class="owl-carousel">
                <div class="item"><img src="{{media url="wysiwyg/gastro/homepage/brand1.png"}}" alt="" style="display: inline-block;" /></div>
                <div class="item"><img src="{{media url="wysiwyg/gastro/homepage/brand2.png"}}" alt="" style="display: inline-block;" /></div>
                <div class="item"><img src="{{media url="wysiwyg/gastro/homepage/brand3.png"}}" alt="" style="display: inline-block;" /></div>
                <div class="item"><img src="{{media url="wysiwyg/gastro/homepage/brand4.png"}}" alt="" style="display: inline-block;" /></div>
                <div class="item"><img src="{{media url="wysiwyg/gastro/homepage/brand5.png"}}" alt="" style="display: inline-block;" /></div>
                <div class="item"><img src="{{media url="wysiwyg/gastro/homepage/brand6.png"}}" alt="" style="display: inline-block;" /></div>
                <div class="item"><img src="{{media url="wysiwyg/gastro/homepage/brand7.png"}}" alt="" style="display: inline-block;" /></div>
            </div>
            <script type="text/javascript">
                require([
                'jquery',
                'owl.carousel/owl.carousel.min'
                ], function ($) {
                    $("#brands-slider .owl-carousel").owlCarousel({
                        autoplay: false,
                        autoplayTimeout: 5000,
                        autoplayHoverPause: true,
                        margin: 0,
                        nav: false,
                        navText: ["<em class='porto-icon-left-open-huge'></em>","<em class='porto-icon-right-open-huge'></em>"],
                        dots: false,
                        loop: false,
                        responsive: {
                            0: {
                                items:2
                            },
                            640: {
                                items:3
                            },
                            768: {
                                items:4
                            },
                            992: {
                                items:5
                            },
                            1200: {
                                items:7
                            }
                        }
                    });
                });
            </script>
        </div>
    </div>
</div>
{{block class="Magento\Cms\Block\Block" block_id="shops_info"}}
<style type="text/css">
    #banner-slider-demo-9 img {width:100%;}
    #banner-slider-demo-9 .content, #ads-slider-demo-9 .content {
        position: absolute;
        z-index: 1;
        color: #fff;
        background-color: #000000;
        padding: 12px 15px 12px;
        border-radius: 3px;
        letter-spacing: 1.6px;
        line-height: 1;
    }
	#banner-slider-demo-9 .content h2, #ads-slider-demo-9 .content h2 {
		font-size: 13px;
		font-weight: bold;
		letter-spacing: 1.6px;
		text-transform: uppercase;
		line-height: 15px;
		margin: 2px 0 0;
	}
	#banner-slider-demo-9 .content span, #ads-slider-demo-9 .content span {
        font-size: 17px;
		text-transform:uppercase;
	}
	#banner-slider-demo-9 .content p {
		font-size:14px;
		font-weight:300;
		margin-bottom:10;
	}
	#banner-slider-demo-9 .content .btn-default {
		font-size: 14px;
		line-height: 25px;
		letter-spacing: 0.025em;
		padding: 10px 34px;
		border-radius:3px;
		background-color: #010204;
		color: #fff;
		font-family: 'Oswald';
		text-transform: uppercase;
		margin-top: 28px;
	}
	#testimonials-slider-demo-9 {
		border: solid 2px #0188cc;
		border-radius: 2px;
    }
    @media (min-width: 768px) and (max-width: 991px) {
        #ads-slider-demo-9 .item img {
            height: 197px;
        }
    }
    @media (min-width: 1200px) {
        #ads-slider-demo-9 .item img {
            height: 335px;
        }
    }
    @media (max-width: 767px) {
        #ads-slider-demo-9 .item img {
            width: 100%;
            height: auto;
        }
    }
	@media (min-width: 768px) {
		.page-header .nav-sections {
			display: none;
		}
		h2.side-menu-title {
			padding: 16px 25px;
		}
        .sw-megamenu.navigation.side-megamenu li.level0 > a {
            margin: 0;
            line-height: 46px;
            font-weight: bold;
            font-size: 16px;
            color: #707070;
        }
        .sw-megamenu.navigation.side-megamenu li.level0 > a img {
            vertical-align: middle;
            margin-right: 12px;
            width: 21px;
        }
	}
	@media (max-width: 767px) {
		#banner-slider-demo-9 img {width:100%;height:100%;}
		#banner-slider-demo-9 .owl-controls {
			display:none !important;
		}
		#banner-slider-demo-9 .content span, #ads-slider-demo-9 .content span {
			font-size: 11px;
        }
        #banner-slider-demo-9 .content h2, #ads-slider-demo-9 .content h2 {
            font-size: 9px;
            line-height: 11px;
        }
		#banner-slider-demo-9 .content .btn-default {
			font-size: 10px !important;
			line-height: 20px;
			padding: 3px 13px;
			border-radius: 3px;
			margin-top: 0px;
		}
    }
    @media (min-width: 768px) {
        .home-top-container {
            display: flex;
            justify-content: space-between;
            margin-top: 10px;
        }
        .home-category {
            width: 18%;
            margin-right: 1.5%;
        }
        .home-banner-main {
            width: 60%;
        }
        .home-banner-right {
            width: 17%;
        }
        .home-side-menu {
            display: block;
        }
    }
    .sw-megamenu.navigation.side-megamenu li.level0.fullwidth > .submenu, .sw-megamenu.navigation.side-megamenu li.level0.staticwidth > .submenu {
        margin-left: 10px !important;
    }
    #featured_products .products-grid .product-item .price-box {
        display: none;
    }
    .recent-posts {
        margin: 50px 0;
    }
    .recent-posts .post-image {
        position: relative;
        display: flex;
        border-radius: 6px 6px 0 0;
        overflow: hidden;
    }
    .recent-posts .post-image img {
        width: 100%;
    }
    .recent-posts .post-image .postTitle {
        padding: 10px 12px;
        border-radius: 3px;
        background: #000000;
        color: #fff;
        left: 15px;
        bottom: 13px;
        position: absolute;
        letter-spacing: 1px;
    }
    .recent-posts .post-image .postTitle span {
        display: block;
        font-size: 16px;
    }
    .recent-posts .post-image .postTitle strong {
        font-size: 12px;
    }
    .recent-posts .post-content {
        display: flex;
        padding: 18px 18px 14px;
        background: #F4F4F4;
        align-items: center;
    }
    .recent-posts .postContent {
        -webkit-line-clamp: 4;
        height: 76px;
    }
    .recent-posts .postContent > p {
        font-size: 12px;
        line-height: 19px;
        letter-spacing: 0.05em;
    }
    .recent-posts .post-content .read-more {
        width: 10%;
    }
    .recent-posts .post-content .read-more > i {
        font-size: 23px;
        color: #aeaeae;
    }
    #brands-slider .owl-stage {
        display: flex;
        align-items: center;
    }
</style>