<div class="home-top-container">
	<div class="home-category">
		<div class="home-side-menu">
			{{block class="Smartwave\Megamenu\Block\Topmenu" name="sw.sidenav" template="Smartwave_Megamenu::sidemenu.phtml" ttl="3600"}}
		</div>
	</div>
	<div class="home-banner-main">
		<div id="banner-slider-demo-9" class="owl-carousel owl-banner-carousel owl-bottom-narrow" style="margin-bottom:20px;">
			<div class="item" style="background:url({{media url="wysiwyg/gastro/homepage/shutterstock_1306579120.jpg"}}) center center no-repeat;background-size:cover;border-radius:2px;">
				<div style="position:relative">
					<img src="{{media url="wysiwyg/gastro/homepage/02.png"}}" alt="" />
					<div class="content content-slide-1" style="top:9%;left:5%;">
						<span style="font-weight: 300">UNSERE</span>
						<h2>EDELSTAHLMÖBEL</h2>
					</div>
				</div>
			</div>
			<div class="item" style="background:url({{media url="wysiwyg/gastro/homepage/shutterstock_1306579120.jpg"}}) center center no-repeat;background-size:cover;border-radius:2px;">
				<div style="position:relative">
					<img src="{{media url="wysiwyg/gastro/homepage/02.png"}}" alt="" />
					<div class="content content-slide-2" style="position:absolute;z-index:1;top:23%;left:8%;text-align:left;">
						<span style="font-size:18px;">OVER <b style="font-size:26px;font-family:'Oswald';">200+</b></span>
						<h2>GREAT DEALS</h2>
						<p style="font-size:14px;font-weight:300;">While they last!</p>
						<a href="{{config path="web/unsecure/base_url"}}electronics.html" class="btn btn-default" style="background-color:#010204;color:#fff;font-family:'Oswald';font-size:14px;letter-spacing:0.025em;font-weight:400;">shop now</a>
					</div>
				</div>
			</div>
			<div class="item" style="background:url({{media url="wysiwyg/gastro/homepage/shutterstock_1306579120.jpg"}}) center center no-repeat;background-size:cover;border-radius:2px;">
				<div style="position:relative">
					<img src="{{media url="wysiwyg/gastro/homepage/02.png"}}" alt="" />
					<div class="content content-slide-3" style="position:absolute;z-index:1;top:23%;left:8%;text-align:left;">
						<span style="font-size:18px;">up to <b style="font-size:26px;font-family:'Oswald';">40%</b> off</span>
						<h2>NEW ARRIVALS</h2>
						<p style="font-size:14px;font-weight:300;">Starting at $9</p>
						<a href="{{config path="web/unsecure/base_url"}}motors.html" class="btn btn-default" style="background-color:#010204;color:#fff;font-family:'Oswald';font-size:14px;letter-spacing:0.025em;font-weight:400;">shop now</a>
					</div>
				</div>
			</div>
		</div>
		<script type="text/javascript">
			require([
				'jquery',
				'owl.carousel/owl.carousel.min'
			], function ($) {
				$("#banner-slider-demo-9").owlCarousel({
					items: 1,
					autoplay: true,
					autoplayTimeout: 5000,
					autoplayHoverPause: true,
					dots: false,
					nav: false,
					navRewind: true,
					animateIn: 'fadeIn',
					animateOut: 'fadeOut',
					loop: true
				});
			});
		</script>
	</div>
    <div class="home-banner-right">
        <div id="ads-slider-demo-9" class="owl-carousel">
            <div class="item">
                <img src="{{media url="wysiwyg/gastro/homepage/shutterstock_1071810413.jpg"}}" alt="" style="display:inline-block;"/>
                <div class="content ads-slide-1" style="bottom:6%;left:7%;">
                    <span style="font-weight: 300">DEINE</span>
                    <h2>KOCHTECHNIK</h2>
                </div>
            </div>
            <div class="item">
                <img src="{{media url="wysiwyg/gastro/homepage/shutterstock_1071810413.jpg"}}" alt="" style="display:inline-block;" />
                <div class="content ads-slide-2" style="bottom:6%;left:7%;">
                    <span style="font-weight: 300">DEINE</span>
                    <h2>KOCHTECHNIK</h2>
                </div>
            </div>
            <div class="item">
                <img src="{{media url="wysiwyg/gastro/homepage/shutterstock_1071810413.jpg"}}" alt="" style="display:inline-block;" />
                <div class="content ads-slide-3" style="bottom:6%;left:7%;">
                    <span style="font-weight: 300">DEINE</span>
                    <h2>KOCHTECHNIK</h2>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            require([
                'jquery',
                'owl.carousel/owl.carousel.min'
            ], function ($) {
                $("#ads-slider-demo-9").owlCarousel({
                    items: 1,
                    autoplay: true,
                    autoplayTimeout: 5000,
                    autoplayHoverPause: true,
                    dots: false,
                    nav: false,
                    navRewind: true,
                    animateIn: 'fadeIn',
                    animateOut: 'fadeOut',
                    loop: true
                });
            });
        </script>
    </div>
</div>
<h2 class="filterproduct-title"><span class="content"><strong>FEATURED ITEMS</strong></span></h2>
<div id="featured_product" class="owl-top-narrow">
    {{block class="Smartwave\Filterproducts\Block\Home\FeaturedList" name="featured_product" product_count="10" aspect_ratio="1" image_width="200" product_type="1" template="owl_list.phtml"}}
</div>
<script type="text/javascript">
    require([
        'jquery',
        'owl.carousel/owl.carousel.min'
    ], function ($) {
        $("#featured_product .owl-carousel").owlCarousel({
            autoplay: true,
            autoplayTimeout: 5000,
            autoplayHoverPause: true,
            loop: true,
            navRewind: true,
            margin: 0,
            nav: false,
            navText: ["<em class='porto-icon-left-open-huge'></em>","<em class='porto-icon-right-open-huge'></em>"],
            dots: true,
            responsive: {
                0: {
                    items:2
                },
                768: {
                    items:3
                },
                992: {
                    items:3
                },
                1200: {
                    items:4
                }
            }
        });
    });
</script>
<div class="row">
    <div class="col-md-4">
        <h2 class="filterproduct-title" style="background-image:none;margin-top:20px;margin-bottom:5px;"><span class="content"><strong>New</strong></span></h2>
        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_small_list" product_count="3" aspect_ratio="0" image_width="212" image_height="212" template="small_list.phtml"}}
    </div>
    <div class="col-md-4">
        <h2 class="filterproduct-title" style="background-image:none;margin-top:20px;margin-bottom:5px;"><span class="content"><strong>Hot</strong></span></h2>
        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_small_list" product_count="3" aspect_ratio="0" image_width="212" image_height="212" template="small_list.phtml"}}
    </div>
    <div class="col-md-4">
        <h2 class="filterproduct-title" style="background-image:none;margin-top:20px;margin-bottom:5px;"><span class="content"><strong>Sale</strong></span></h2>
        {{block class="Smartwave\Filterproducts\Block\Home\LatestList" name="latest_small_list" product_count="3" aspect_ratio="0" image_width="212" image_height="212" template="small_list.phtml"}}
    </div>
</div>
<div class="shop-features" style="background-color:#fff; margin-top:13px;">
    <div class="row">
        <div class="col-md-4" style="margin-bottom: 10px;">
            <em class="porto-icon-star"></em>
            <h3>DEDICATED SERVICE</h3>
            <p>Consult our specialists for help with an order, customization, or design advice.</p>
            <a href="#">Get in Touch</a>
        </div>
        <div class="col-md-4" style="margin-bottom: 10px;">
            <em class="porto-icon-reply"></em>
            <h3>FREE RETURNS</h3>
            <p>We stand behind our goods and services and want you to be satisfied with them.</p>
            <a href="#">Returns Policy</a>
        </div>
        <div class="col-md-4" style="margin-bottom: 10px;">
            <em class="porto-icon-paper-plane"></em>
            <h3>INTERNATIONAL SHIPPING</h3>
            <p>Currently over 50 countries qualify for express international shipping.</p>
            <a href="#">Learn More</a>
        </div>
    </div>
</div>
<div class="single-images">
    <div class="row" style="margin-left:-10px;margin-right:-10px;">
        <div class="col-md-4" style="padding-left:10px;padding-right:10px;padding-bottom:15px;">
            <a class="image-link" href="#">
                <img src="{{media url="wysiwyg/smartwave/porto/homepage/09/content/img1.jpg"}}" alt="" />
            </a>
        </div>
        <div class="col-md-4" style="padding-left:10px;padding-right:10px;padding-bottom:15px;">
            <a class="image-link" href="#">
                <img src="{{media url="wysiwyg/smartwave/porto/homepage/09/content/img2.jpg"}}" alt="" />
            </a>
        </div>
        <div class="col-md-4" style="padding-left:10px;padding-right:10px;padding-bottom:15px;">
            <a class="image-link" href="#">
                <img src="{{media url="wysiwyg/smartwave/porto/homepage/09/content/img3.jpg"}}" alt="" />
            </a>
        </div>
    </div>
</div>
<style type="text/css">
    #banner-slider-demo-9 img {width:100%;}
    #banner-slider-demo-9 .content, #ads-slider-demo-9 .content {
        position: absolute;
        z-index: 1;
        color: #fff;
        background-color: #000000;
        padding: 12px 15px 12px;
        border-radius: 3px;
        letter-spacing: 1.6px;
        line-height: 1;
    }
	#banner-slider-demo-9 .content h2, #ads-slider-demo-9 .content h2 {
		font-size: 13px;
		font-weight: bold;
		letter-spacing: 1.6px;
		text-transform: uppercase;
		line-height: 15px;
		margin: 2px 0 0;
	}
	#banner-slider-demo-9 .content span, #ads-slider-demo-9 .content span {
        font-size: 17px;
		text-transform:uppercase;
	}
	#banner-slider-demo-9 .content p {
		font-size:14px;
		font-weight:300;
		margin-bottom:10;
	}
	#banner-slider-demo-9 .content .btn-default {
		font-size: 14px;
		line-height: 25px;
		letter-spacing: 0.025em;
		padding: 10px 34px;
		border-radius:3px;
		background-color: #010204;
		color: #fff;
		font-family: 'Oswald';
		text-transform: uppercase;
		margin-top: 28px;
	}
	#testimonials-slider-demo-9 {
		border: solid 2px #0188cc;
		border-radius: 2px;
    }
    #ads-slider-demo-9 .item img {
        height: 335px;
    }
	@media (min-width: 768px) {
		.page-header .nav-sections {
			display: none;
		}
		h2.side-menu-title {
			padding: 16px 25px;
		}
        .sw-megamenu.navigation.side-megamenu li.level0 > a {
            margin: 0;
            line-height: 46px;
            font-weight: bold;
            font-size: 16px;
            color: #707070;
        }
        .sw-megamenu.navigation.side-megamenu li.level0 > a img {
            vertical-align: middle;
            margin-right: 12px;
            width: 21px;
        }
	}
	@media (max-width: 767px) {
		#banner-slider-demo-9 img {width:100%;height:100%;}
		#banner-slider-demo-9 .owl-controls {
			display:none !important;
		}
		#banner-slider-demo-9 .content span, #ads-slider-demo-9 .content span {
			font-size: 11px;
        }
        #banner-slider-demo-9 .content h2, #ads-slider-demo-9 .content h2 {
            font-size: 9px;
            line-height: 11px;
        }
		#banner-slider-demo-9 .content .btn-default {
			font-size: 10px !important;
			line-height: 20px;
			padding: 3px 13px;
			border-radius: 3px;
			margin-top: 0px;
		}
    }
    @media (min-width: 992px) {
        .home-top-container {
            display: flex;
            justify-content: space-between;
            margin-top: 10px;
        }
        .home-category {
            width: 18%;
            margin-right: 1.5%;
        }
        .home-banner-main {
            width: 60%;
        }
        .home-banner-right {
            width: 17%;
        }
    }
    .sw-megamenu.navigation.side-megamenu li.level0.fullwidth > .submenu, .sw-megamenu.navigation.side-megamenu li.level0.staticwidth > .submenu {
        margin-left: 10px !important;
    }
</style>