<div class="content-signup">
    <a class="action primary" href="#"><?=__('Register Your Organization Now')?></a>
    <p>You will receive a confirmation email with a temporary password.  You can start building your cart and submit for quotes immediately.  Once we review and approve your account we will update your pricing.</p>
    <p>We look forward to helping you get the best quality products at the best possible prices.</p>
</div>